Declare Boost includes are "system"
Because Boost is always an external dependency, doing so allows the
compiler to not emit warnings when they occur in Boost headers: e.g.,
GCC 4.2.1 complains about one of the Boost 1.55.0 header files as:

  .../boost/fusion/tuple/detail/preprocessed/tuple.hpp:21:7: error:
  no newline at end of file

Newer versions of GCC do not consider this bug even worth a warning,
but 1) it nonetheless is, and 2) this would prevent us from potential
breakage due to Boost headers in the future, since appleseed it built
with -Werror by default.